# Generated by Django 5.2 on 2025-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('fuel', models.CharField(default='Essence', max_length=30)),
                ('transmission', models.CharField(default='Manuelle', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
